version: '3'

services:
  cassandra:
    image: cassandra:jammy
    
    ports:
      - "7000:7000" # Cluster communication
      - "7001:7001" # SSL
      - "9042:9042" # Native protocol
      - "7199:7199" # JMX
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./cassandra/cassandra.yaml:/etc/cassandra/default.conf/cassandra.yaml

    environment:
      - CASSANDRA_CLUSTER_NAME=test-cluster
      - CASSANDRA_NUM_TOKENS=256
    networks:
      - cassandra_network
    
volumes:
  cassandra_data:
networks:
  cassandra_network:
